name: NPCPlugin
version: '${project.version}'
main: lkc.npcplugin.NPCPlugin
api-version: 1.18
depend: [ Citizens ]
softdepend: [ event ]
commands:
  settingnpc:
    description: npc 세팅
    usage: /<command>
