name: httpconnection
version: '${project.version}'
main: lkc.httpconnection.httpconnection
api-version: 1.18
commands:
  gethttp:
    usage: /<command>
    description: http get method test

  posthttp:
    usage: /<command>
    description: http post method test